#!/usr/bin/env node
/**
 * MCP Server for IBM DB2 LUW
 *
 * Spawns a persistent Java subprocess (Db2Gateway) that maintains a JDBC
 * connection to DB2 LUW. The Node.js process handles the MCP stdio protocol.
 *
 * Environment variables:
 *   DB2_HOSTNAME   - DB2 host (default: localhost)
 *   DB2_PORT       - DB2 port (default: 50000)
 *   DB2_DATABASE   - Database name (default: trunkdb)
 *   DB2_USERNAME   - DB2 username (required)
 *   DB2_PASSWORD   - DB2 password (required)
 *   DB2_SCHEMA     - Default schema for metadata queries (optional)
 *   DB2_JDBC_JAR   - Path to db2jcc4.jar (default: bundled)
 *   QUERY_MAX_LIMIT - Max rows returned per query (default: 1000)
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { spawn } from "child_process";
import { createRequire } from "module";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { Buffer } from "buffer";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require   = createRequire(import.meta.url);
const pkg       = require("./package.json");

// ── Configuration ────────────────────────────────────────────────────────────

const cfg = {
  hostname:    process.env.DB2_HOSTNAME  || "localhost",
  port:        process.env.DB2_PORT      || "50000",
  database:    process.env.DB2_DATABASE  || "trunkdb",
  username:    process.env.DB2_USERNAME,
  password:    process.env.DB2_PASSWORD,
  schema:      (process.env.DB2_SCHEMA   || "").toUpperCase(),
  maxLimit:    parseInt(process.env.QUERY_MAX_LIMIT || "1000", 10),
  gatewayJar:  join(__dirname, "java", "Db2Gateway.jar"),
  db2jccJar:   process.env.DB2_JDBC_JAR || join(__dirname, "java", "db2jcc4.jar"),
};

const jdbcUrl = `jdbc:db2://${cfg.hostname}:${cfg.port}/${cfg.database}:useIdentityValLocalForAutoGeneratedKeys=true;`;

// ── Java gateway ──────────────────────────────────────────────────────────────

let gateway        = null;
let lineBuffer     = "";
let requestCounter = 0;
const pending      = new Map();  // id → { resolve, reject }

function startGateway() {
  return new Promise(async (resolve, reject) => {
    const CP_SEP = process.platform === "win32" ? ";" : ":";
    const classpath = [cfg.gatewayJar, cfg.db2jccJar].join(CP_SEP);

    gateway = spawn(
      "java",
      ["-cp", classpath, "Db2Gateway"],
      {
        env: {
          ...process.env,
          DB2_JDBC_URL: jdbcUrl,
          DB2_USER:     cfg.username,
          DB2_PASSWORD: cfg.password,
        },
        stdio: ["pipe", "pipe", "pipe"],
      }
    );

    gateway.stderr.on("data", (d) => process.stderr.write(d));

    gateway.stdout.on("data", (chunk) => {
      lineBuffer += chunk.toString("utf8");
      const lines = lineBuffer.split("\n");
      lineBuffer = lines.pop();           // keep partial last line

      for (const raw of lines) {
        const line = raw.trim();
        if (!line) continue;
        let msg;
        try {
          msg = JSON.parse(line);
        } catch {
          process.stderr.write(`[db2-luw] Unparseable gateway output: ${line}\n`);
          continue;
        }

        if (msg.ready === true)  { resolve();  continue; }
        if (msg.ready === false) { reject(new Error(msg.error || "Gateway failed to start")); continue; }

        const req = pending.get(msg.id);
        if (req) {
          pending.delete(msg.id);
          msg.error ? req.reject(new Error(msg.error)) : req.resolve(msg);
        }
      }
    });

    gateway.on("error", reject);
    gateway.on("exit", (code) => {
      if (code !== 0) reject(new Error(`Java gateway exited with code ${code}`));
    });

    // Safety timeout — if "ready" never arrives within 30 s, fail
    setTimeout(() => reject(new Error("Gateway startup timed out after 30 s")), 30_000);
  });
}

function dbQuery(sql, params = []) {
  return new Promise((resolve, reject) => {
    const id         = String(++requestCounter);
    const b64sql     = Buffer.from(sql,  "utf8").toString("base64");
    const b64params  = params.map((p) => Buffer.from(String(p ?? ""), "utf8").toString("base64"));
    const line       = [id, b64sql, ...b64params].join("\t") + "\n";

    pending.set(id, { resolve, reject });
    gateway.stdin.write(line);
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function markdownTable(result) {
  const { columns = [], rows = [], rowCount } = result;
  if (!rows.length) return `No rows returned.`;

  const widths = columns.map((c, i) =>
    Math.max(c.length, ...rows.map((r) => String(r[i] ?? "").length))
  );
  const header = "| " + columns.map((c, i) => c.padEnd(widths[i])).join(" | ") + " |";
  const sep    = "| " + widths.map((w) => "-".repeat(w)).join(" | ") + " |";
  const body   = rows.map(
    (r) => "| " + r.map((v, i) => String(v ?? "").padEnd(widths[i])).join(" | ") + " |"
  );
  return [header, sep, ...body].join("\n") + `\n\n_(${rowCount ?? rows.length} rows)_`;
}

function effectiveSchema(argSchema) {
  return ((argSchema || cfg.schema) || "").toUpperCase() || null;
}

// ── MCP server ────────────────────────────────────────────────────────────────

const server = new Server(
  { name: pkg.name, version: pkg.version },
  { capabilities: { tools: {} } }
);

// List tools
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "list_schemas",
      description: "List all schemas (libraries) in the DB2 LUW database.",
      inputSchema: {
        type: "object",
        properties: {
          filter: { type: "string", description: "LIKE pattern, % = wildcard (e.g. 'ONS%')" },
        },
      },
    },
    {
      name: "list_tables",
      description: "List all tables in a schema. Uses DB2_SCHEMA env var if schema not provided. Optionally filter by name pattern using % as wildcard.",
      inputSchema: {
        type: "object",
        properties: {
          schema: { type: "string", description: "Schema name (default: DB2_SCHEMA env var)" },
          filter: { type: "string", description: "LIKE pattern for table name, % = wildcard" },
        },
      },
    },
    {
      name: "describe_table",
      description: "Get detailed column information for a specific table including data types, lengths, nullability and defaults.",
      inputSchema: {
        type: "object",
        required: ["table"],
        properties: {
          schema: { type: "string" },
          table:  { type: "string", description: "Table name" },
        },
      },
    },
    {
      name: "list_views",
      description: "List all views in a schema.",
      inputSchema: {
        type: "object",
        properties: {
          schema: { type: "string" },
          filter: { type: "string" },
        },
      },
    },
    {
      name: "list_indexes",
      description: "List all indexes for a specific table including uniqueness and column information.",
      inputSchema: {
        type: "object",
        required: ["table"],
        properties: {
          schema: { type: "string" },
          table:  { type: "string" },
        },
      },
    },
    {
      name: "get_table_constraints",
      description: "Get all constraints (primary keys, foreign keys, unique) for a specific table.",
      inputSchema: {
        type: "object",
        required: ["table"],
        properties: {
          schema: { type: "string" },
          table:  { type: "string" },
        },
      },
    },
    {
      name: "execute_query",
      description: "Execute a read-only SQL SELECT query against the DB2 LUW database. Only SELECT statements are allowed. Results are limited by default.",
      inputSchema: {
        type: "object",
        required: ["sql"],
        properties: {
          sql:    { type: "string", description: "SQL SELECT query to execute" },
          params: { type: "array",  items: { type: "string" }, description: "Prepared statement parameters" },
          limit:  { type: "number", description: `Max rows to return (default: ${cfg.maxLimit})` },
        },
      },
    },
  ],
}));

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params;

  try {
    switch (name) {
      // ── list_schemas ──────────────────────────────────────────────────────
      case "list_schemas": {
        const filter = args.filter || "%";
        const result = await dbQuery(
          "SELECT SCHEMANAME FROM SYSCAT.SCHEMATA WHERE SCHEMANAME LIKE ? ORDER BY SCHEMANAME",
          [filter]
        );
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── list_tables ───────────────────────────────────────────────────────
      case "list_tables": {
        const schema = effectiveSchema(args.schema);
        const filter = (args.filter || "%").replace("*", "%");

        let sql, params;
        if (schema) {
          sql    = "SELECT TABNAME, TYPE, REMARKS FROM SYSCAT.TABLES WHERE TABSCHEMA = ? AND TABNAME LIKE ? ORDER BY TABNAME";
          params = [schema, filter];
        } else {
          sql    = "SELECT TABNAME, TABSCHEMA, TYPE, REMARKS FROM SYSCAT.TABLES WHERE TABNAME LIKE ? ORDER BY TABSCHEMA, TABNAME";
          params = [filter];
        }
        const result = await dbQuery(sql, params);
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── describe_table ────────────────────────────────────────────────────
      case "describe_table": {
        const schema = effectiveSchema(args.schema);
        if (!schema) throw new Error("schema is required (or set DB2_SCHEMA env var)");
        const result = await dbQuery(
          `SELECT COLNAME, TYPENAME, LENGTH, SCALE, NULLS, "DEFAULT", REMARKS
             FROM SYSCAT.COLUMNS
            WHERE TABSCHEMA = ? AND TABNAME = ?
            ORDER BY COLNO`,
          [schema, args.table.toUpperCase()]
        );
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── list_views ────────────────────────────────────────────────────────
      case "list_views": {
        const schema = effectiveSchema(args.schema);
        const filter = (args.filter || "%").replace("*", "%");
        let sql, params;
        if (schema) {
          sql    = "SELECT VIEWNAME, REMARKS FROM SYSCAT.VIEWS WHERE VIEWSCHEMA = ? AND VIEWNAME LIKE ? ORDER BY VIEWNAME";
          params = [schema, filter];
        } else {
          sql    = "SELECT VIEWNAME, VIEWSCHEMA, REMARKS FROM SYSCAT.VIEWS WHERE VIEWNAME LIKE ? ORDER BY VIEWSCHEMA, VIEWNAME";
          params = [filter];
        }
        const result = await dbQuery(sql, params);
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── list_indexes ──────────────────────────────────────────────────────
      case "list_indexes": {
        const schema = effectiveSchema(args.schema);
        if (!schema) throw new Error("schema is required (or set DB2_SCHEMA env var)");
        const result = await dbQuery(
          `SELECT INDNAME, COLNAMES, UNIQUERULE, INDEXTYPE
             FROM SYSCAT.INDEXES
            WHERE TABSCHEMA = ? AND TABNAME = ?
            ORDER BY INDNAME`,
          [schema, args.table.toUpperCase()]
        );
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── get_table_constraints ─────────────────────────────────────────────
      case "get_table_constraints": {
        const schema = effectiveSchema(args.schema);
        if (!schema) throw new Error("schema is required (or set DB2_SCHEMA env var)");
        const result = await dbQuery(
          `SELECT C.CONSTNAME, C.TYPE, K.COLNAME, K.COLSEQ,
                  R.REFTABSCHEMA, R.REFTABNAME
             FROM SYSCAT.TABCONST C
             JOIN SYSCAT.KEYCOLUSE K
               ON K.CONSTNAME = C.CONSTNAME AND K.TABSCHEMA = C.TABSCHEMA AND K.TABNAME = C.TABNAME
        LEFT JOIN SYSCAT.REFERENCES R
               ON R.CONSTNAME = C.CONSTNAME AND R.TABSCHEMA = C.TABSCHEMA AND R.TABNAME = C.TABNAME
            WHERE C.TABSCHEMA = ? AND C.TABNAME = ?
            ORDER BY C.CONSTNAME, K.COLSEQ`,
          [schema, args.table.toUpperCase()]
        );
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      // ── execute_query ─────────────────────────────────────────────────────
      case "execute_query": {
        const upperSql = args.sql.trim().toUpperCase();
        if (!upperSql.startsWith("SELECT") && !upperSql.startsWith("WITH") && !upperSql.startsWith("VALUES")) {
          throw new Error("Only SELECT/WITH/VALUES queries are allowed.");
        }
        const limit = Math.min(args.limit ?? cfg.maxLimit, cfg.maxLimit);
        let sql = args.sql.trim();
        if (!upperSql.includes("FETCH FIRST") && !upperSql.includes("LIMIT ")) {
          sql += ` FETCH FIRST ${limit} ROWS ONLY`;
        }
        const result = await dbQuery(sql, args.params || []);
        return { content: [{ type: "text", text: markdownTable(result) }] };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (err) {
    return {
      content: [{ type: "text", text: `**Error:** ${err.message}` }],
      isError: true,
    };
  }
});

// ── Bootstrap ─────────────────────────────────────────────────────────────────

async function main() {
  process.stderr.write(`[db2-luw] Starting ${pkg.name} v${pkg.version}\n`);
  process.stderr.write(`[db2-luw] Connecting to ${cfg.hostname}:${cfg.port}/${cfg.database}\n`);

  try {
    await startGateway();
    process.stderr.write(`[db2-luw] DB2 LUW connection established.\n`);
  } catch (err) {
    process.stderr.write(`[db2-luw] Warning: DB2 connection failed: ${err.message}\n`);
    process.stderr.write(`[db2-luw] Server starting anyway — queries will return errors until DB2 is reachable.\n`);
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  process.stderr.write(`[db2-luw] Fatal: ${err.message}\n`);
  process.exit(1);
});

